<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExecutiveDocumentation.Application\ExecutiveDocumentation.Application.csproj" />
    <ProjectReference Include="..\ExecutiveDocumentation.Infrastructure\ExecutiveDocumentation.Infrastructure.csproj" />
    <ProjectReference Include="..\ExecutiveDocumentation.Contracts\ExecutiveDocumentation.Contracts.csproj" />
  </ItemGroup>

</Project>
